### ISSUE TITLE
Please share To Do List

### ISSUE THREAD

**Issue by GeorgeS2019** [GuilhermeGSousa/godot-motion-matching#10]
Godot 4.4 has latest SkeletonModifier for IK

I have seen a list of new changes, not sure how these new changes different significantly from previous

**Comment by GuilhermeGSousa** [comment]
I'll write up some issues of what I think this repo needs, for me or anyone else to implement. I like the idea of implementing the IK post processing pass using the new `SkeletonModifier`. 

I've also thought about using that node to implement blending, but internalization for example needs to know when an animation changes to work correctly, which  `SkeletonModifier` doesn't have out of the box.

Anyways I digress, I'll write this stuff down on a couple of issues

**Comment by GeorgeS2019** [comment]
Join the Godot contributor Chat. 12 th Sept animation online meeting, people have many questions for U and update

**Comment by GuilhermeGSousa** [comment]
I'll be populating this as this repo evolves.
https://github.com/GuilhermeGSousa/godot-motion-matching/projects?query=is%3Aopen

@GeorgeS2019 I'm on the contributors chat, but the meeting the 12th might be too late in the evening for my timezone. Could point me to the questions people had? Happy to answer however I can
