### ISSUE TITLE
Purpose of the PR?

### ISSUE THREAD

**Issue by GeorgeS2019** [GuilhermeGSousa/godot-motion-matching#40]
Now using **V-Sekai-fire**, previously **V-Sekai**
https://github.com/GuilhermeGSousa/godot-motion-matching/pull/39

![Screenshot_2024-10-13-20-44-53-081-edit_com microsoft emmx](https://github.com/user-attachments/assets/2fbda077-42ef-489d-90c7-d244f7862c6b)

**Comment by GeorgeS2019** [comment]
Reference:

https://github.com/Remi123/MotionMatching/pull/16

**Comment by GuilhermeGSousa** [comment]
I'll wait until its out of "draft" state to review, but its an improvement to our CI. I'd ask that you direct your questions related to it to the PR itself though, I'll therefore close this issue.

**Comment by GeorgeS2019** [comment]
# CI stops working

![image](https://github.com/user-attachments/assets/8e338a63-c009-4692-9d6e-80d433d3d86c)
