### ISSUE TITLE
Implement Motion Matching as an `AnimationRootNode`

### ISSUE THREAD

**Issue by GuilhermeGSousa** [GuilhermeGSousa/godot-motion-matching#41]
As the API for motion matching evolves, its becoming clear that motion matching should be implemented as an `AnimationRootNode`, that receives its query inputs as a parameter. As I see it, the advantages to this would be:
- Being able to mix whatever comes out of motion matching with other animation (like using MM for locomotion mixed with an animation for aiming a weapon).
- Easier to implement blending when switching animations on MM queries

There are some changes required at the engine level to be able to do this:
- https://github.com/godotengine/godot/pull/97020#issuecomment-2395130663
- The `_process` method of `AnimationRootNode` is currently marked as deprecated, and a supported version of that might only be coming when structs are available in the engine [(see this thread)](https://chat.godotengine.org/channel/animation?msg=dgdS9BLb3pGkzDgQP)

**Comment by fire** [comment]
Are you working on this openly?

**Comment by GuilhermeGSousa** [comment]
I am! I am starting to learn that the only way to do it on Godot's latest version is through a custom module, the GDExtension bindings aren't in a place where extending a `AnimationRootNode` is doable (and probably won't be until structs are in the engine). The way I see it right now we either:
- Use a hacky fork of godot that allows us to set this up, until structs are implemented.
- Refactor this repo to be a custom module instead. We then either eventually make this an official engine plugin, or turn it back into a GDExtension once extending `AnimationRootNode`s is supported by the engine.

I'm curious to know what you think!

**Comment by fire** [comment]
I've done this before with a different project. This is a practical way of implementing motion matching.

https://github.com/V-Sekai/godot/tree/vsk-motion-matching-4.3/modules/motion_matching

https://github.com/V-Sekai/motion_matching

**Comment by fire** [comment]
I use https://github.com/ingydotnet/git-subrepo to import a standalone git repo into a branch of godot engine.

**Comment by GuilhermeGSousa** [comment]
This is perfect, making a submodule out of a directory of this repo is just what I need, I'll set that up. This repo has a working motion matching implementation, but I now think the correct way of doing it for a 1.0 version is to have motion matching queries run on animation nodes. The two big advantages of this approach imo:
- We could blend motion matching output with other anims, especially useful for walking + aiming
- If each motion matching node runs queries on a specific animation library, we could then use state machines to run queries on smaller libraries, and switch between them based on state. This would make queries run faster and choose more appropriate animations.

I saw V-Sekai and Remi's motion matching implementation, I also had the chance to discuss this with him!

**Comment by fire** [comment]
I agree with this approach!

**Comment by fire** [comment]
My dream for when we get the basic implementation is to also implement https://peizhuoli.github.io/walkthedog/index.html

**Comment by fire** [comment]
You may have missed the branch for module https://github.com/V-Sekai/motion_matching/tree/module

**Comment by fire** [comment]
Are you on discord? I exceeded my friend limit of 1000 so if we want to talk it'll have to be the V-Sekai discord here. 

https://linktr.ee/chibifire

**Comment by GuilhermeGSousa** [comment]
I am! I'll ping you on discord

**Comment by GuilhermeGSousa** [comment]
Just joined the discord!

**Comment by GeorgeS2019** [comment]
@fire 

https://github.com/GuilhermeGSousa/godot-motion-matching/issues/41#issuecomment-2436441892
It is important to respect where the codes come from

https://github.com/V-Sekai/godot/tree/vsk-motion-matching-4.3/modules/motion_matching is basically copy from Remi without **clearly acknowledging.** 

https://github.com/V-Sekai/motion_matching is simply clearly stating that it is a fork.

Both links provided come from one same source. One is a fork, One is copying without acknowledging. 

In both cases, there are no evidence that the CI works.

This ethical in respecting others contribution is critical in Godot community project and the foundation of  trust-worthiness collaboration.

**Comment by fire** [comment]
The code https://github.com/V-Sekai/godot/blob/vsk-motion-matching-4.3/modules/motion_matching/LICENSE clearly acknowledges Remi.

**Comment by GeorgeS2019** [comment]
@fire

I appreciate your enthusiasm:

I want to trust your enthusiasm  I know your strengths :  Please make sure your codes are CI working before recommending merger. 

When I work with Malcolm  This is what I learned from him

**Comment by fire** [comment]
The primary HEAD of development is https://github.com/GuilhermeGSousa/godot-motion-matching/tree/engine-module.

The cicd for the branch is failing https://github.com/GuilhermeGSousa/godot-motion-matching/pull/42

![image](https://github.com/user-attachments/assets/24fb9023-1bef-4fbd-bc6d-1cadd3f6baa5)

So that's what I'm working on.

**Comment by GeorgeS2019** [comment]
@fire 

Yes,  please help this project to get the CI working in reliable way

I know you have a lot of experience in this area. 

The community depends on you  :-)

**Comment by fire** [comment]
Notes from トカゲ

> To explain the fundamental design, AnimationTree does not have a process for playing back animations; AnimationNodeAnimation does all the work for playback
AnimationNodeAnimation generates/stores a timeline from the length of each animation, manages the playback position, and passes it to the AnimationMixer.
>
> So, if you do not want to write such playback position management from scratch, you should refer to AnimationNodeTransitio or AnimationBlendSpace2D, which blend multiple AnimationNodeAnimation AnimationNode.
>
> There you don't need to manage the playback position, just seek instructions and blend amount adjustments to the AnimationNodes connected as a result of the matching

**Comment by fire** [comment]
I have marked all non motion-matching node discussions as offtopic.

**Comment by GuilhermeGSousa** [comment]
Done! Yey!
