### ISSUE TITLE
Debug 3d extension doesn't work on double builds

### ISSUE THREAD

**Issue by fire** [GuilhermeGSousa/godot-motion-matching#65]
Need to upgrade debug 3d extension or replace with gdscript.

**Comment by fire** [comment]
Update to https://github.com/DmitriySalnikov/godot_debug_draw_3d/issues/57 to resolve the crash.

**Comment by GuilhermeGSousa** [comment]
An issue for https://github.com/GuilhermeGSousa/godot-motion-matching-demo instead, I'll fix it there
