### ISSUE TITLE
starting a demo project in 4.4 dev7

### ISSUE THREAD

**Issue by VicPrzz00** [GuilhermeGSousa/godot-motion-matching#79]
Hi y'all, first of all I love the progress done and the fact that there is someone working on motion matching for Godot(I'm a big fan of it). Hope you can continue working on it!

Now that animation node extension has been added, does the gdextension work or do I need to build it? How do I make a project to test it?

**Comment by GuilhermeGSousa** [comment]
Yes that's normal, one of the changes needed there is to add the extension dlls. The motion matching folder there is just a symlink that I'm using for development

**Comment by VicPrzz00** [comment]
I see, I'm gonna wait for the update. Thank you once again for your dedication and effort in making motion matching a thing in Godot
